apiVersion: v1
kind: Namespace
metadata:
  name: retail-app
  labels:
    name: retail-app
    project: bedrock
    environment: production
  annotations:
    description: "Namespace for InnovateMart Retail Store Application"